<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
     // To create a function that handles async tasks, you need to use async keyword before the function
     // async function always returns a Promise.
     async function test() {
         // If a return value is not promise, it uses as wrapper to conver it. Promise.resolve(10)
         // Promise.resolve is a static method, and it returns a Promise which is fullfilled (resolved)
        return 10 ;   // Promise.resolve(10)
     }

     test().then(val => console.log(`Test result is ${val}`));

     // Or it can return a Promise explicityly
     async function waitForTwo() {
         return new Promise((resolve, reject) => {
             setTimeout(() => { resolve()}, 2000) ;
         })
     }

     waitForTwo().then(() => console.log("Two seconds elapsed."));

     // async function has a keyword "await" which is similar to "yield" in generator functions.
     // It waits the fullfillment (resolve or reject) of a Promise, if the async task resolves or rejects, it resumes
     // the execution. 
     // The nice thing of "await" is that it DOES NOT BLOCK the execution of the code. 
     // It silently quits from the function execution, and when the promise is fullfilled, it resumes.
     // Syntax :  await  Promise
     // await can be used only within async function

     async function waitForThree() {
         await new Promise((resolve, reject) => {
             setTimeout(() => { resolve()}, 3000) ;
         }) ;

         // This part is like then() of promise.
         console.log("Three seconds elapsed.")
     }
     waitForThree() ;

     // Calling an asynch function within a normal function.
     function  normalFunction() {
    
         waitForThree().then(() => console.log("waitForThree finished in synch function")) ;
         console.log("normal") ;
     }
     normalFunction() ;

     // try/catch error handler

     async function ErrorTest() {
         try {
             let num = await new Promise( (resolve, reject) => {
                 setTimeout(() => {
                     let rnd = Math.floor(Math.random() * 10) ;
                     if ( rnd < 5) reject(rnd) ;
                     resolve(rnd) ;  // if a Promise is fullfilled by reject/resolve before, it cannot be fullfilled again.
                 })
             }, 500);
         } catch(err) {
             console.log(`Number (${err}) is too low `);
         }
     }

     ErrorTest() ;

    </script>
</body>
</html>